### PR TITLE
Fix incorrect paths in node security guide

### PR DESCRIPTION
**Pull request by jshufro**

### CODE REVIEW

**Comment by nickdoherty** [comment]
~ resolves to /home/username on Linux and /Users/username on Mac

Probably best to keep it as ~ but happy to discuss. Was there a specific issue that triggered this PR?

**Comment by davnex** [comment]
nestorsn49@gmail.com

**Comment by jshufro** [comment]
> ~ resolves to /home/username on Linux and /Users/username on Mac
> 
> Probably best to keep it as ~ but happy to discuss. Was there a specific issue that triggered this PR?

The issue is that `~/username` on linux resolves to `/home/username/username` which is nonsensical.

**Comment by nickdoherty** [comment]
Makes sense. Do you have any objection to making it simply
```
~/
```
?

**Comment by jshufro** [comment]
> Makes sense. Do you have any objection to making it simply
> 
> ```
> ~/
> ```
> 
> ?

Hang on, there's a few places this needs to be massaged if we want multiplatform

**Comment by nickdoherty** [comment]
``` ~/ ``` is used a lot through out the docs site, seems that the securing your node page is the only place that uses ``` ~/username ```.

**Pull request merged**
